### ISSUE TITLE
Unable to replicate decoding: missing a file with lengths

### ISSUE THREAD

**Issue by jindrahelcl** [nyu-dl/dl4mt-seqgen#1]
Hi,

when I try to run `eval_scripts/generate.sh`, it complains that a file `de2en_lengths.pkl` does not exist. Now, the `train.sh` script did not create such file, nor there is a script that generates one. It is not included with the pretrained models, either.

From what I gathered, the file should contain a src-tgt mapping of lengths, but I can't really tell what the contents should be, so it would be great if you could provide a script that generates this.

Thanks!

**Comment by mansimov** [comment]
I forgot to include those files, thanks for noticing it.

Here is the link to dataset with updated files https://drive.google.com/file/d/149vO36tEE5Nyh7-pvqAs_3yhS7GfxME0/view?usp=sharing
I have updated README as well

**Comment by jindrahelcl** [comment]
That does not look ok, the archive contains only three files, `codes`, `train.de-en.de.tok` (only 26MB, ~190k lines), and `vocab.de-en`.

**Comment by mansimov** [comment]
Oops thats an archive with not fully downloaded train dataset

This one should be correct https://drive.google.com/file/d/11hZN2bctJsGOBUx6of5en4eZw-A66mQs/view?usp=sharing
