### ISSUE TITLE
Reproduce the baseline model

### ISSUE THREAD

**Issue by jindrahelcl** [nyu-dl/dl4mt-seqgen#2]
Hi,
is there a script for reproducing the baseline (autoregressive) results from your paper? Did you use the XLM toolkit/can it be trained using this codebase, or does the baseline model come from a different toolkit?

Thanks!

**Comment by mansimov** [comment]
Hi,

I will push pretrained models and scripts to train them tomorrow
Baselines comes from the same toolkit

**Comment by mansimov** [comment]
Updated the repo with links to pretrained baseline autoregressive models and scripts to train/eval them.
Let me know if you have questions

**Comment by jindrahelcl** [comment]
Thanks for the models and scripts!

I have a problem running the autoregressive trainers on multiple GPUs though.. It seems there are some unused parameters in the model and Pytorch's DistributedDataParallel module does not like that. 

The error I'm getting is:
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.
 This error indicates that your module has parameters that were not used in producing its output
 (the return value of `forward`). You can enable unused parameter detection by passing the keyword 
argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`. If you already 
have this argument set, then the distributed data parallel module wasn't able to locate the output 
tensors in the return value of your module's `forward` function. Please include the structure of the return 
value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
```

However, setting `find_unused_parameters` to True didn't quite do the trick, so I still don't know which parameters are unused. I tried to run this on a different environment and I got a message which was looking like this: https://github.com/pytorch/pytorch/issues/18180

**Comment by jindrahelcl** [comment]
I tried to train the model both from scratch and with `--reload-model` option specified as in the example scripts.

**Comment by mansimov** [comment]
Oh yeah I had this problem as well.

You need to use Pytorch 0.4.1 for autoregressive models. Just create separate conda environment with Pytorch 0.4.1 and try running the code with pretrained models

**Comment by jindrahelcl** [comment]
Yes, that works.. Thanks
